
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 13;
  public static final int AND = 15;
  public static final int LT = 18;
  public static final int ELSE = 8;
  public static final int PLUS = 11;
  public static final int RBRACE = 26;
  public static final int RPAREN = 24;
  public static final int OR = 16;
  public static final int INT = 5;
  public static final int THEN = 7;
  public static final int SEMI = 22;
  public static final int WHILE = 9;
  public static final int NOT = 20;
  public static final int RETURN = 10;
  public static final int IF = 6;
  public static final int LBRACE = 25;
  public static final int LPAREN = 23;
  public static final int GT = 19;
  public static final int ID = 2;
  public static final int COMMA = 27;
  public static final int EOF = 0;
  public static final int NUMBER = 3;
  public static final int DIVIDE = 14;
  public static final int MINUS = 12;
  public static final int error = 1;
  public static final int ASSIGN = 21;
  public static final int EQEQ = 17;
  public static final int VOID = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "NUMBER",
  "VOID",
  "INT",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "RETURN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "AND",
  "OR",
  "EQEQ",
  "LT",
  "GT",
  "NOT",
  "ASSIGN",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA"
  };
}

