
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 9;
  public static final int LBRACE = 14;
  public static final int INT = 6;
  public static final int DIVIDE = 11;
  public static final int MAIN = 5;
  public static final int NUMBER = 3;
  public static final int VOID = 4;
  public static final int SEMI = 7;
  public static final int PLUS = 8;
  public static final int EOF = 0;
  public static final int ID = 2;
  public static final int ASSIGN = 16;
  public static final int error = 1;
  public static final int RPAREN = 13;
  public static final int TIMES = 10;
  public static final int RBRACE = 15;
  public static final int LPAREN = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "NUMBER",
  "VOID",
  "MAIN",
  "INT",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "ASSIGN"
  };
}

